# Namespace naming convetion <org>-<context>-<env>
# Every cluster values-<cluster>.yaml file has unique <env> entries listed
org: myorg
context: go-app

# default values if unset for each environment
defaults:
  source:
    path: deploy/helm/app
    repoURL: 'https://github.com/trevorbox/gitops-example-iac-go.git'
    targetRevision: main
