apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hr-echo-{{ .Values.cluster.name }}
spec:
  generators:
    - git:
        repoURL: 'https://github.com/trevorbox/gitops-example-iac-go.git'
        revision: main
        files:
          - path: {{ printf "argocd/clusters/%s/namespaces/*.yaml" .Values.cluster.name }}
  template:
    metadata:
      name: >-
        {{ printf "hr-echo-{{env}}" }}
    spec:
      project: default
      source:
        path: deploy/helm/app
        repoURL: 'https://github.com/trevorbox/gitops-example-iac-go.git'
        targetRevision: >-
          {{ printf "{{targetRevision}}" }}
        helm:
          valueFiles:
            - {{ printf "values-{{env}}.yaml" }}
      destination:
        server: {{ printf "{{server}}"  | quote }}
        namespace: >-
          {{ printf "hr-echo-{{env}}" }}
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        preserveResourcesOnDeletion: {{ printf "{{preserveResourcesOnDeletion}}" | quote }}
